### ISSUE TITLE
name collision (Vagrant)

### ISSUE THREAD

**Issue by fschwiet** [nessos/Vagabond#1]
Vagrant is already a thing (http://www.vagrantup.com/, http://www.amazon.com/s/ref=nb_sb_noss_1?url=search-alias%3Daps&field-keywords=vagrant) and though its not as popular in the .NET community it is growing in popularity.  I think to reduce confusion you might want to call your library something else.

**Comment by kbrowns** [comment]
I highly recommend renaming your library.  Vagrant is very popular in many circles and growing.  Trademarks aside, this will be a consistent source of confusion for everyone.

**Comment by ghuntley** [comment]
Agreed. Came across your lib via the #fsharpsydney meetup and it's not good when a slide has to be prefixed by "it's not the vagrant you are thinking about if you come from a unix background"

**Comment by mick-wilson** [comment]
+1

**Comment by eiriktsarpalis** [comment]
Library has been renamed to Vagabond.
